name: Deployment Pipeline for API and Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 025016447278.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image (API)
        run: |
          docker build -t quicktasks-api ./server

      - name: Tag Docker Image (API)
        run: |
          docker tag quicktasks-api:latest 025016447278.dkr.ecr.us-east-1.amazonaws.com/damitech/quicktasks-api:latest

      - name: Push Docker Image to AWS ECR (API)
        run: |
          docker push 025016447278.dkr.ecr.us-east-1.amazonaws.com/damitech/quicktasks-api:latest

      - name: ECS Service Deployment (API)
        run: |
          aws ecs update-service \
            --cluster prod-cluster \
            --service prod-quicktasks-api \
            --force-new-deployment \
            --region us-east-1

  frontend-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    # needs: api-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 025016447278.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image (Frontend)
        run: |
          docker build -t quicktasks-frontend ./client

      - name: Tag Docker Image (Frontend)
        run: |
          docker tag quicktasks-frontend:latest 025016447278.dkr.ecr.us-east-1.amazonaws.com/damitech/quicktasks-frontend:latest

      - name: Push Docker Image to AWS ECR (Frontend)
        run: |
          docker push 025016447278.dkr.ecr.us-east-1.amazonaws.com/damitech/quicktasks-frontend:latest

      - name: ECS Service Deployment (Frontend)
        run: |
          aws ecs update-service \
            --cluster prod-cluster \
            --service prod-quicktasks-frontend \
            --force-new-deployment \
            --region us-east-1
