name: Deployment Pipeline for API Service

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Push and deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 025016447278.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t quicktasks ./server

      - name: Tag Docker Image
        run: |
          docker tag quicktasks:latest 025016447278.dkr.ecr.us-east-1.amazonaws.com/damitech/quicktasks:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 025016447278.dkr.ecr.us-east-1.amazonaws.com/damitech/quicktasks:latest

      - name: ECS Service Deployment
        run: |
          aws ecs update-service \
            --cluster prod-cluster \
            --service prod-quicktasks-service \
            --force-new-deployment \
            --region us-east-1