name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Sync Static Files to S3 (Assets with Caching)
        run: |
          aws s3 sync build/ s3://damitech.xyz \
            --delete \
            --exclude "*.html" \
            --cache-control "max-age=31536000,public"

      - name: Sync HTML Files to S3 (No Cache)
        run: |
          aws s3 sync build/ s3://damitech.xyz \
            --exclude "*" \
            --include "*.html" \
            --cache-control "no-cache"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3PLZQZGV5NYWM \
            --paths "/*"
